version: "3"

services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./data/mysql:/var/lib/mysql
    expose:
      - "3306"

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    restart: always
  